DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
AWS_ACCESS_KEY_ID="AKIAJ3MLYFRKPVNCV37A"
AWS_SECRET_ACCESS_KEY="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"
AWS_STORAGE_BUCKET_NAME="openscience"
